### ISSUE TITLE
Not able to set any parameters other than frequency!

### ISSUE THREAD

**Issue by shubham9436** [balamuruganky/Ublox_Linux_Library#4]
Hi,

I have not been able to set any other parameters like Dynamic Model, Enable Disable GPS, etc though frequency gets updated successfully. Through u-center application I am able to configure all the parameters.

```
    Stream seriComm("/dev/ttyACM0");
    seriComm.begin(115200);
    if (!seriComm.isConnected()) {
        printf("Ublox is not connected. Please connect ublox GNSS module and try again...\n");
        return 0;
    }

    myGNSS.begin(seriComm);
    myGNSS.enableGNSS(false, SFE_UBLOX_GNSS_ID_GALILEO);
    myGNSS.setDynamicModel(DYN_MODEL_STATIONARY);
```
They always return false. Also, when I update frequency using ```myGNSS.setNavigationFrequency(1)```
and try to retrieve the frequency using ```myGNSS.getNavigationFrequency()```, then first, it returns the old value and I need to call ```myGNSS.getNavigationFrequency()``` function to get the updated frequency.

**Comment by balamuruganky** [comment]
@shubham9436 : Could you please use saveConfigSelective function to save the configuration before calling getter function? Thanks.

**Comment by shubham9436** [comment]
Thank you for the reply. So using saveConfigSelective(VAL_CFG_SUBSEC_NAVCONF) works for getting the Navigation Frequency at once but other setter functions still do not work.
Here's piece of code:
 ```
uint32_t currentUART2Baud = myGNSS.getVal32(UBLOX_CFG_UART2_BAUDRATE);
    cout<<"currentUART2Baud: "<<currentUART2Baud<<endl;
    bool response = true;
    if (currentUART2Baud != 57600)
    {
        response &= myGNSS.setVal32(UBLOX_CFG_UART2_BAUDRATE, 57600);
        if (!response)
            cout<<"SetVal failed"<<endl;
        else
            cout<<"SetVal succeeded"<<endl;
    }
    else
        cout<<"No baud change needed";
    myGNSS.saveConfigSelective(VAL_CFG_SUBSEC_IOPORT);
    uint32_t currentUART2Baud1 = myGNSS.getVal32(UBLOX_CFG_UART2_BAUDRATE);
    cout<<"currentUART2Baud: "<<currentUART2Baud1<<endl;
```

Output of the code is:
```
/dev/pts/23 is connected successfully!!!

/dev/ttyACM0 is connected successfully!!!
Stream : Closed

/dev/ttyACM0 is connected successfully!!!
currentUART2Baud: 38400
SetVal failed
currentUART2Baud: 38400
Stream : Closed
Stream : Closed
```

Similarly when I try to set the dynamic model using `setDynamicModel()` function, it always returns false.

**Comment by balamuruganky** [comment]
@shubham9436 : Good to know! I wonder do you really want to change the baud rate of the UART during runtime? I believe, changing UART configuration dynamically is not a good practice. The below code piece shows how to set baud rate during initialization for the connected device.

    Stream seriComm(argv[1]);
    seriComm.begin(38400);

If baud rate has been changed then the seriComm object can't connect with the device.

However, could you please list down the setter which is not functioning correctly other than UART configurations. Did you try to reproduce this issue in Arduino? This repository doesn't change any piece of code from the sparkfun arduino library. 

I haven't had any device at the moment to reproduce this issue. Please let me know the list of setter that are failing.

Thanks.

**Comment by shubham9436** [comment]
> @shubham9436 : Good to know! I wonder do you really want to change the baud rate of the UART during runtime? I believe, changing UART configuration dynamically is not a good practice. The below code piece shows how to set baud rate during initialization for the connected device.
> 
> ```
> Stream seriComm(argv[1]);
> seriComm.begin(38400);
> ```
> 
> If baud rate has been changed then the seriComm object can't connect with the device.
> 
> However, could you please list down the setter which is not functioning correctly other than UART configurations. Did you try to reproduce this issue in Arduino? This repository doesn't change any piece of code from the sparkfun arduino library.
> 
> I haven't had any device at the moment to reproduce this issue. Please let me know the list of setter that are failing.
> 
> Thanks.

No, I do not want to change the baud rate of the UART during runtime, it's just I was randomly checking the setter functions.
I'll try to check the setter functions and will list it down and also I am trying to arrange the Arduino board.

**Comment by shubham9436** [comment]
I have started with 
```
//    myGNSS.setVal32(UBLOX_CFG_UART2_BAUDRATE, 57600);
//    myGNSS.setDynamicModel(DYN_MODEL_STATIONARY);
//    myGNSS.enableGNSS(false, SFE_UBLOX_GNSS_ID_GALILEO);
//    myGNSS.setStaticPosition(xxx, xxx, 800, true);
//    myGNSS.setSurveyMode(SVIN_MODE_ENABLE, 1000, 10);
```
And none of them works. I have kind of feeling that setter functions are not working at all. Let me know if I am doing anything wrong. Here's my whole code
```
#include "SparkFun_u-blox_GNSS_Arduino_Library.h"
#include <iostream>

unsigned int microsecond = 1000000;

using namespace std;
SFE_UBLOX_GNSS myGNSS;

int main(__attribute__((unused)) int argc, char **argv) {
    Stream seriComm("/dev/ttyACM0");
    seriComm.begin(115200);
    if (!seriComm.isConnected()) {
        printf("Ublox is not connected. Please connect ublox GNSS module and try again...\n");
        return 0;
    }
    myGNSS.begin(seriComm);
//    myGNSS.setVal32(UBLOX_CFG_UART2_BAUDRATE, 57600);
//    myGNSS.setDynamicModel(DYN_MODEL_STATIONARY);
//    myGNSS.enableGNSS(false, SFE_UBLOX_GNSS_ID_GALILEO);
//    myGNSS.setStaticPosition(xxx, xxx, 800, true);
//    myGNSS.setSurveyMode(SVIN_MODE_ENABLE, 1000, 10)
    return 1;
}

```

**Comment by balamuruganky** [comment]
@shubham9436 : Did you save the configuration (saveConfigSelective)?

**Comment by shubham9436** [comment]
> @shubham9436 : Did you save the configuration (saveConfigSelective)?

All these methods always return false. So I assume that the parameters have not been set.

**Comment by balamuruganky** [comment]
@shubham9436 : Below are the two functions write the configurations to the device. Please add some prints in Stream header file and debug further.

	size_t write(uint8_t byte) {
		m_IsAvailable = false;
		return ::write(m_SerialFd, (void *)&byte, sizeof(byte));
	}

	size_t write(uint8_t *byte, size_t num_of_bytes) {
		m_IsAvailable = false;
		return ::write(m_SerialFd, byte, num_of_bytes);
	}

I haven't had any device at the moment. Thanks for bringing this issue.

**Comment by shubham9436** [comment]
> @shubham9436 : Below are the two functions write the configurations to the device. Please add some prints in Stream header file and debug further.
> 
> ```
> size_t write(uint8_t byte) {
> 	m_IsAvailable = false;
> 	return ::write(m_SerialFd, (void *)&byte, sizeof(byte));
> }
> 
> size_t write(uint8_t *byte, size_t num_of_bytes) {
> 	m_IsAvailable = false;
> 	return ::write(m_SerialFd, byte, num_of_bytes);
> }
> ```
> 
> I haven't had any device at the moment. Thanks for bringing this issue.

```
    cout<<endl<<"Navigation Frequency"<<endl;
    cout<<myGNSS.setNavigationFrequency(1);
    cout<<endl<<"Baud rate"<<endl;
    cout<<unsigned (myGNSS.setVal32(UBLOX_CFG_UART2_BAUDRATE, 57600));
    cout<<endl<<"Dynamic Model"<<endl;
    cout<<myGNSS.setDynamicModel(DYN_MODEL_STATIONARY);
    cout<<endl<<"GPS"<<endl;
    cout<<myGNSS.enableGNSS(false, SFE_UBLOX_GNSS_ID_GALILEO);
    cout<<endl<<"Survey IN"<<endl;
    cout<<myGNSS.setSurveyMode(SVIN_MODE_ENABLE, 1000, 10);
    cout<<endl;
```
The last value indicates the return value (boolean) of the setter function.
Output:
```
Navigation Frequency
181 98 6 8 0 0 14 48 181 98 6 8 6 0 232 3 1 0 1 0 1 57 1
Baud rate
181 98 6 138 12 0 0 7 0 0 1 0 83 64 0 225 0 0 24 72 0
Dynamic Model
181 98 6 36 0 0 42 132 181 98 6 36 36 0 1 0 2 3 0 0 0 0 16 39 0 0 10 0 250 0 250 0 100 0 94 1 0 60 0 0 0 0 0 0 0 0 0 0 0 0 136 99 0
GPS
181 98 6 62 0 0 68 210 0
Survey IN
181 98 6 113 0 0 119 107 0
```

**Comment by balamuruganky** [comment]
@shubham9436 : It looks like only first command always succeeds!

**Comment by shubham9436** [comment]
> @shubham9436 : It looks like only first command always succeeds!

No, it's not the case. Apart from ```setNavigationFrequency()```, none of them works. Also, when I change the order and keep ```setNavigationFrequency()``` at the last, then it always fails.
```
Survey IN
181 98 6 113 0 0 119 107 0
Navigation Frequency
181 98 6 8 0 0 14 48 0
Stream : Closed
```

**Comment by balamuruganky** [comment]
@shubham9436 : set Navigation frequency config is failing because the stream is closed. Hmm... It is seems to be a serious bug. Since, I have no device at the moment, can't help much on this. I would suggest you to debug Stream header file write functions.

**Comment by shubham9436** [comment]
> @shubham9436 : set Navigation frequency config is failing because the stream is closed. Hmm... It is seems to be a serious bug. Since, I have no device at the moment, can't help much on this. I would suggest you to debug Stream header file write functions.

I'll try to debug. Meanwhile, if we could connect online and you could help me, it would accelerate us to resolve the issue as I am little less acquainted with C++ programming language. Email-ID: shubhambaranwal2000@gmail.com

**Comment by balamuruganky** [comment]
Timing issue during serial communication caused this issue. I suggested @shubham9436 to change the code accordingly. Would expect pull request. Thanks.
